server:
  port: 8082
  servlet:
    context-path: /api

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.sa-east-1.amazonaws.com/sa-east-1_l06uKIzHL
